//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using DataAccess.Models;
    using System;
    using System.Collections.Generic;
    
    public partial class Ad:BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ad()
        {
            this.Videos = new HashSet<Video>();
        }
    
      
        public string PrerolTitle { get; set; }
        public string Preroll { get; set; }
        public string MidrollTitle { get; set; }
        public string Midroll { get; set; }
        public string PostrollTitle { get; set; }
        public string Postroll { get; set; }
        public Nullable<int> PrerollHit { get; set; }
        public Nullable<int> MidrollHit { get; set; }
        public Nullable<int> PostrollHit { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }

        public Nullable<int> User_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video> Videos { get; set; }
        public virtual User User { get; set; }
    }
}
