//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using DataAccess.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Album : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.Categories = new HashSet<Category>();
            this.AlbumIMGs = new HashSet<AlbumIMG>();
        }
        [Display(Name ="Baþlýk")]
        [DataType(DataType.Text)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Title { get; set; }

        [Display(Name = "Açýklama")]
        [DataType(DataType.MultilineText)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Description { get; set; }
        
        [Display(Name = "Görsel")]
        public string Img { get; set; }

        [Display(Name = "Görsel Açýklama")]
        [DataType(DataType.MultilineText)]
        [System.ComponentModel.DataAnnotations.Required]
        public string ImgDescription { get; set; }


        [Display(Name = "Yayýn Tarihi")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTime PublishDate { get; set; }

        [Display(Name = "Týklama")]
        public int Hit { get; set; }

        public string url { get; set; }
        public int UserId { get; set; }
        public string MainSliderIMG { get; set; }
        public string SidebarIMG { get; set; }
        public string SliderBottomIMG { get; set; }
        public string BestWeeklyIMG { get; set; }
        public string BestWeeklySmIMG { get; set; }
        public string DetailsIMG { get; set; }
        public string OtherIMG { get; set; }

        [Display(Name = "Editör")]
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumIMG> AlbumIMGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
