//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using DataAccess.Models;
    using System;
    using System.Collections.Generic;
    
    public partial class Reklam : BaseEntity
    {
        //public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Img { get; set; }
        public int Hit { get; set; }
        public string EmbedUrl { get; set; }
        //public System.DateTime PublishDate { get; set; }
        //public System.DateTime CreatedDate { get; set; }
        //public System.DateTime UpdatedDate { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public int User_Id { get; set; }
        public string url { get; set; }
    }
}
