//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using DataAccess.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Video : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.Categories = new HashSet<Category>();
        }
    
        //public int Id { get; set; }

        [Display(Name = "Baþlýk")]
        [DataType(DataType.Text)]
        public String Title { get; set; }

        [Display(Name = "Açýklama")]
        [DataType(DataType.Text)]
        public String Description { get; set; }

        [Display(Name = "Yayýn Tarihi")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTime PublishDate { get; set; }

        [Display(Name = "Týklama")]
        public int Hit { get; set; }

        [Display(Name = "Görsel")]
        [DataType(DataType.ImageUrl)]
        public String Img { get; set; } = @"/Storage/Video\defaultNews.jpg";

        public string MainSliderIMG { get; set; }
        public string SidebarIMG { get; set; }
        public string SliderBottomIMG { get; set; }
        public string BestWeeklyIMG { get; set; }
        public string BestWeeklySmIMG { get; set; }
        public string DetailsIMG { get; set; }
        public string OtherIMG { get; set; }
        public string url { get; set; }

        [Display(Name = "Video")]
        //[DataType(DataType.Url)]
        public String EmbedUrl { get; set; }

        public Nullable<int> User_Id { get; set; }

        [Display(Name = "Paylasan Kisi")]
        public virtual User User { get; set; }

        [Display(Name = "Video Kategorileri")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }

    }
}
